<?php

namespace Oni4i\FakeNzGenerator\Resource;

class CityResource implements ResourceInterface
{
    public static function extract(): array
    {
        return [
            "Ahaura",
            "Ahipara",
            "Akaroa",
            "Albany",
            "Alexandra",
            "Amberley",
            "Aoraki Mount Cook",
            "Apiti",
            "Aria",
            "Arrowtown",
            "Arthur's Pass",
            "Ashburton",
            "Ashhurst",
            "Athol",
            "Atiamuri",
            "Auckland",
            "Awanui",
            "Balclutha",
            "Balfour",
            "Belfast",
            "Benneydale",
            "Blackball",
            "Blenheim",
            "Bluff",
            "Bombay",
            "Brighton",
            "Brightwater",
            "Broadwood",
            "Bruce Bay",
            "Bulls",
            "Bunnythorpe",
            "Burnham",
            "Cable Bay",
            "Cambridge",
            "Carterton",
            "Cave",
            "Charleston",
            "Chatham Islands",
            "Cheviot",
            "Christchurch",
            "Clarks Beach",
            "Clevedon",
            "Clinton",
            "Clive",
            "Clyde",
            "Coalgate",
            "Collingwood",
            "Colville",
            "Coopers Beach",
            "Coromandel",
            "Cromwell",
            "Culverden",
            "Cust",
            "Dairy Flat",
            "Dannevirke",
            "Darfield",
            "Dargaville",
            "Diamond Harbour",
            "Dipton",
            "Dobson",
            "Doyleston",
            "Drury",
            "Dunedin",
            "Dunsandel",
            "Duvauchelle",
            "Edendale",
            "Edgecumbe",
            "Eketahuna",
            "Eltham",
            "Fairlie",
            "Featherston",
            "Feilding",
            "Fox Glacier",
            "Foxton",
            "Franz Josef Glacier",
            "French Pass",
            "Garston",
            "Geraldine",
            "Gisborne",
            "Glenorchy",
            "Gordonton",
            "Gore",
            "Granity",
            "Great Barrier Island",
            "Greta Valley",
            "Greymouth",
            "Greytown",
            "Haast",
            "Hamilton",
            "Hampden",
            "Hanmer Springs",
            "Harihari",
            "Haruru",
            "Hastings",
            "Haumoana",
            "Hautapu",
            "Havelock",
            "Havelock North",
            "Hawarden",
            "Hawera",
            "Hector",
            "Helensville",
            "Henderson",
            "Hicks Bay",
            "Hikuai",
            "Hikurangi",
            "Himatangi Beach",
            "Hinds",
            "Hokitika",
            "Hororata",
            "Horotiu",
            "Houhora",
            "Howick",
            "Hunterville",
            "Huntly",
            "Hunua",
            "Ikamatua",
            "Inangahua",
            "Inglewood",
            "Invercargill",
            "Kaeo",
            "Kaiapoi",
            "Kaikohe",
            "Kaikoura",
            "Kairaki",
            "Kaitaia",
            "Kaitangata",
            "Kaiwaka",
            "Kamo",
            "Kaponga",
            "Karamea",
            "Karori",
            "Katikati",
            "Kaukapakapa",
            "Kawakawa",
            "Kawerau",
            "Kawhia",
            "Kerikeri",
            "Kimbolton",
            "Kingston",
            "Kirwee",
            "Kohukohu",
            "Kotemaori",
            "Kumara",
            "Kumeu",
            "Kurow",
            "Lake Hawea",
            "Lake Tekapo",
            "Lawrence",
            "Leeston",
            "Leigh",
            "Leithfield",
            "Levin",
            "Lincoln",
            "Little River",
            "Lower Hutt",
            "Lumsden",
            "Lyttelton",
            "Mahia",
            "Mahoenui",
            "Makarora",
            "Mamaku",
            "Manaia",
            "Manakau",
            "Manapouri",
            "Mangakino",
            "Mangaweka",
            "Mangawhai",
            "Mangonui",
            "Manurewa",
            "Manutuke",
            "Mapua",
            "Martinborough",
            "Marton",
            "Maruia",
            "Masterton",
            "Matakana",
            "Matakohe",
            "Matamata",
            "Matangi",
            "Matata",
            "Mataura",
            "Matawai",
            "Matiere",
            "Maungakaramea",
            "Maungatapere",
            "Maungaturoto",
            "Mercer",
            "Meremere",
            "Methven",
            "Middlemarch",
            "Milford Sound",
            "Millers Flat",
            "Milton",
            "Moana",
            "Moerewa",
            "Mokau",
            "Morrinsville",
            "Mosgiel",
            "Mossburn",
            "Motu",
            "Motueka",
            "Mount Maunganui",
            "Mount Ruapehu",
            "Murchison",
            "Murupara",
            "Napier",
            "Naseby",
            "National Park",
            "Nelson",
            "New Lynn",
            "New Plymouth",
            "Ngakawau",
            "Ngaruawahia",
            "Ngatea",
            "Ngunguru",
            "Nightcaps",
            "Norsewood",
            "Nuhaka",
            "Oakura",
            "Oamaru",
            "Ohai",
            "Ohakune",
            "Ohaupo",
            "Ohinewai",
            "Ohope",
            "Ohura",
            "Okaihau",
            "Okato",
            "Omakau",
            "Omapere",
            "Omarama",
            "Omokoroa",
            "One Tree Point",
            "Onerahi",
            "Ongaonga",
            "Ongarue",
            "Oparau",
            "Opononi",
            "Opotiki",
            "Opua",
            "Opunake",
            "Orere Point",
            "Orewa",
            "Otaki",
            "Otane",
            "Otautau",
            "Otematata",
            "Otorohanga",
            "Oturehua",
            "Outram",
            "Owaka",
            "Owhango",
            "Oxford",
            "Paekakariki",
            "Paeroa",
            "Pahiatua",
            "Paihia",
            "Palmerston",
            "Palmerston North",
            "Papakura",
            "Papamoa",
            "Paparoa",
            "Parakai",
            "Paraparaumu",
            "Pareora",
            "Patea",
            "Patumahoe",
            "Patutahi",
            "Pauanui",
            "Peel Forest",
            "Pegasus",
            "Picton",
            "Piha",
            "Piopio",
            "Pirongia",
            "Pleasant Point",
            "Pokeno",
            "Pongaroa",
            "Porangahau",
            "Porirua",
            "Port Chalmers",
            "Prebbleton",
            "Puhoi",
            "Pukeatua",
            "Pukekohe",
            "Pukerua Bay",
            "Putaruru",
            "Queenstown",
            "Raetihi",
            "Raglan",
            "Rai Valley",
            "Rakaia",
            "Ranfurly",
            "Rangiora",
            "Ratana",
            "Raupunga",
            "Rawene",
            "Red Beach",
            "Reefton",
            "Renwick",
            "Reporoa",
            "Rewa",
            "Richmond",
            "Riverhead",
            "Riversdale",
            "Riverton",
            "Riwaka",
            "Rolleston",
            "Rongotea",
            "Ross",
            "Rotherham",
            "Rotorua",
            "Roxburgh",
            "Ruakaka",
            "Ruatoria",
            "Ruawai",
            "Runanga",
            "Russell",
            "Saint Arnaud",
            "Sanson",
            "Seddon",
            "Sefton",
            "Shannon",
            "Sheffield",
            "Silverdale",
            "Snells Beach",
            "Southbridge",
            "Spring Creek",
            "Springfield",
            "Springs Junction",
            "Springston",
            "St Andrews",
            "Stewart Island",
            "Stirling",
            "Stratford",
            "Tai Tapu",
            "Taihape",
            "Taipa",
            "Tairua",
            "Takaka",
            "Takanini",
            "Takapau",
            "Taneatua",
            "Tangimoana",
            "Tangiteroria",
            "Tapanui",
            "Tapawera",
            "Tarras",
            "Taumarunui",
            "Taupiri",
            "Taupo",
            "Tauranga",
            "Te Anau",
            "Te Araroa",
            "Te Aroha",
            "Te Awamutu",
            "Te Awanga",
            "Te Horo",
            "Te Karaka",
            "Te Kauwhata",
            "Te Kopuru",
            "Te Kuiti",
            "Te Mata",
            "Te Puia Springs",
            "Te Puke",
            "Te Teko",
            "Te Uku",
            "Temuka",
            "Thames",
            "The Pines Beach",
            "Tikitiki",
            "Timaru",
            "Tiniroto",
            "Tinui",
            "Tirau",
            "Tokanui",
            "Tokomaru",
            "Tokomaru Bay",
            "Tokoroa",
            "Tolaga Bay",
            "Tuai",
            "Tuakau",
            "Tuamarina",
            "Tuatapere",
            "Turakina",
            "Turangi",
            "Turua",
            "Tutira",
            "Tutukaka",
            "Twizel",
            "Upper Hutt",
            "Upper Moutere",
            "Urenui",
            "Waddington",
            "Waharoa",
            "Waiau",
            "Waiau Pa",
            "Waiheke Island",
            "Waihi",
            "Waihi Beach",
            "Waihola",
            "Waikaia",
            "Waikanae",
            "Waikari",
            "Waikouaiti",
            "Waikuku Beach",
            "Waimamaku",
            "Waimana",
            "Waimangaroa",
            "Waimate",
            "Waimauku",
            "Waimiha",
            "Wainuiomata",
            "Waiotira",
            "Waiouru",
            "Waipapa",
            "Waipara",
            "Waipawa",
            "Waipu",
            "Waipukurau",
            "Wairoa",
            "Waitara",
            "Waitati",
            "Waitoa",
            "Waitomo",
            "Waitotara",
            "Waiuku",
            "Wakefield",
            "Wallacetown",
            "Walton",
            "Wanaka",
            "Ward",
            "Warkworth",
            "Warrington",
            "Waverley",
            "Wedderburn",
            "Wellington",
            "Wellsford",
            "West Melton",
            "Westport",
            "Whakatane",
            "Whakatu",
            "Whangamata",
            "Whanganui",
            "Whangaparaoa",
            "Whangarei",
            "Whataroa",
            "Whatawhata",
            "Whiritoa",
            "Whitford",
            "Whitianga",
            "Winchester",
            "Winton",
            "Woodend",
            "Woodville",
            "Wyndham"
        ];
    }
}
